import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home({data}) {
    console.log(data)
  return (
    <main className={inter.className}>
      <Head>
        <title>Pokemon Task Fetch SSR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"d-flex justify-content-center align-items-center"}>
          <h1>Hi!</h1>
          <Link href={"/pokemons"}>List of Pokemons </Link>
      </div>
    </main>
  );
}
